# -*- coding:utf-8 -*-

"""
ETF系统常量配置

Author: Claude Code
Date: 2025-01-22
"""

# Redis配置
DEFAULT_REDIS_HOST = "localhost"
DEFAULT_REDIS_PORT = 6379
DEFAULT_REDIS_DB = 0

# 订单配置
DEFAULT_BATCH_SIZE = 100
MAX_BATCH_SIZE_CANCEL = 100
MAX_BATCH_SIZE_SEND = 100
DEFAULT_BATCH_ID = 51232

# 客户端订单ID默认值
DEFAULT_CLIENT_ORDER_ID = "16559590087220001"

# 网络配置
DEFAULT_API_TIMEOUT = 10  # 秒
DEFAULT_RETRY_ATTEMPTS = 3
DEFAULT_RETRY_DELAY = 1.0  # 秒

# 精度配置
DEFAULT_PRICE_PRECISION = 4
DEFAULT_AMOUNT_PRECISION = 2

# 时间间隔配置
DEFAULT_SLEEP_INTERVAL = 0.1  # 秒
DEFAULT_KLINE_INTERVAL = 60  # 秒

# 风险控制
DEFAULT_MAX_POSITION = 100000
DEFAULT_STOP_LOSS_THRESHOLD = 0.02
DEFAULT_VOLATILITY_THRESHOLD = 0.01

# 洗盘交易
DEFAULT_MAX_TRADE_AMOUNT = 50
DEFAULT_MIN_TRADE_VALUE = 5  # USDT

# 性能监控
PERFORMANCE_LOG_INTERVAL = 300  # 秒，5分钟

# 文件路径
NET_VALUE_FILE_PREFIX = "net_value_"
NETVALUE_REDIS_PREFIX = "netvalue_"

# 订单类型
ORDER_TYPE_LIMIT = "LIMIT"
ORDER_TYPE_MARKET = "MARKET"

# 订单方向
SIDE_BUY = "BUY"
SIDE_SELL = "SELL"

# 时间有效性
TIME_IN_FORCE_GTC = "GTC"
TIME_IN_FORCE_IOC = "IOC"
TIME_IN_FORCE_FOK = "FOK"

# 业务类型
BIZ_TYPE_SPOT = "SPOT"

# 日志格式
LOG_FORMAT = "%(asctime)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s"